---
# tasks file for ansible-role-cyrus-sasl

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Get all SASL users
  shell: "{{ cyrus_sasl_sasldblistusers_command }} | cut -f1 -d':'"
  register: register_sasldblistusers
  changed_when: false

- name: Assert cyrus_sasl_sasldblistusers_command ran successfully
  assert:
    that:
      register_sasldblistusers.rc == 0

- name: Delete SASL users
  shell: "{{ cyrus_sasl_saslpassword_command }} -a '{{ item.value.appname }}' -u '{{ item.value.domain }}' -d -f '{{ cyrus_sasl_sasldb_file }}' '{{ item.key }}'"
  with_dict: "{{ cyrus_sasl_user }}"
  no_log: yes
  when:
    - item.value.state == 'absent'
    - item.key ~ '@' ~ item.value.domain in register_sasldblistusers.stdout_lines

- name: Create SASL users
  shell: "echo -n {{ item.value.password }} | {{ cyrus_sasl_saslpassword_command }} -a '{{ item.value.appname }}' -u '{{ item.value.domain }}' -c -p -f '{{ cyrus_sasl_sasldb_file }}' {{ item.key }}"
  with_dict: "{{ cyrus_sasl_user }}"
  no_log: yes
  when:
    - item.value.state == 'present'
    - not item.key ~ '@' ~ item.value.domain in register_sasldblistusers.stdout_lines

- name: Create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Create sasl_check_pw.py
  # XXX this script assumes dbm file
  copy:
    src: files/sasl_check_pw.py
    dest: /usr/local/bin/sasl_check_pw
    mode: 0755

- name: See whose password in sasldb needs update
  command: "/usr/local/bin/sasl_check_pw '{{ cyrus_sasl_sasldb_file }}' '{{ item.key }}' '{{ item.value.domain }}'"
  environment:
    userPassword: "{{ item.value.password }}"
  register: register_sasl_check_pw
  with_dict: "{{ cyrus_sasl_user }}"
  changed_when: false
  no_log: yes
  when:
    - item.value.state == 'present'

- name: Set password if necessary
  shell: "echo -n '{{ item.item.value.password }}' | {{ cyrus_sasl_saslpassword_command }} -p -f {{ cyrus_sasl_sasldb_file }} -u '{{ item.item.value.domain }}' '{{ item.item.key }}'"
  with_items: "{{ register_sasl_check_pw.results }}"
  no_log: yes
  when:
    - "'does not match' in item.stdout_lines"
